<?php
$current_cust_email = "";
if(Mage::getSingleton('customer/session')->isLoggedIn()) {
     $current_cust_email = Mage::getSingleton('customer/session')->getCustomer()->getEmail();
 }
?>

<div style="height: 847px; display: none;" class="window-overlay" id="window-overlay"></div>

<div style="display: none;" class="remember-me-popup" id="remember-me-popup-emailnotify">
	<!-- Popup Header Part -->
    <div class="remember-me-popup-head">
        <h3><?php echo $this->__('Email Notify');?></h3>
        <a title="Close" class="remember-me-popup-close" href="javascript:">
			<?php echo $this->__('Close');?>
		</a>
    </div>
	
	<!-- Popup Body Part -->
    <div class="remember-me-popup-body">	
		<div class="email_notify_popup">
			<div id="email_notify" class="input-box">		
				<div id="email_notify_head">
					<?php echo $this->__('Notify me when this product is in stock:');?>
				</div>
				
				<input type="hidden" name="email_notify_product" id="email_notify_product" value="" />
				
				<input type="hidden" name="email_notify_url" id="email_notify_url" value="<?php echo $this->getUrl('emailnotify/index/emailnotify');?>" />
				
				<input type="text" name="email_notify_text" id="email_notify_text" class="input-text " placeholder="Enter The Email Id" value="<?php echo $current_cust_email; ?>" autocomplete="off" />			
				&nbsp;&nbsp;&nbsp;
				<button class="button" title="Email Notify" type="button" onclick="return notify_email();">
					<span>
						<span><?php echo $this->__('Notify Me');?></span>
					</span>
				</button>
				
				<div id="email_notify_success" class="link-wishlist paddtop">
					<span><?php echo $this->__('You will be Notified by Email when it becomes available.');?></span>
				</div> 
				
				<div id="email_notify_loader">&nbsp;</div>
				
			</div>
		</div>
		
		<!-- Popup Footer Part -->
        <div class="remember-me-popup-close-button a-right">
            <a title="Close" class="remember-me-popup-close button" href="javascript:">
				<span><?php echo $this->__('Close');?></span>
			</a>
        </div>
    </div>
</div>


<script type="text/javascript">
    function toggleRememberMepopupEmailNotify(event)
	{
        if($('remember-me-popup-emailnotify')){
		
            var viewportHeight = document.viewport.getHeight(),
                docHeight      = $$('body')[0].getHeight(),
                height         = docHeight > viewportHeight ? docHeight : viewportHeight;
            $('remember-me-popup-emailnotify').toggle();
            $('window-overlay').setStyle({ height: height + 'px' }).toggle();
        }
		$('email_notify_text').focus();
    }
	
    document.observe("dom:loaded", function() {
        new Insertion.Bottom($$('body')[0], $('window-overlay'));
        new Insertion.Bottom($$('body')[0], $('remember-me-popup-emailnotify'));
        $$('#remember-me-popup-emailnotify .remember-me-popup-close').each(function(element){
            Event.observe(element, 'click', toggleRememberMepopupEmailNotify);
        })
    });
		
	function popup_email_notify(product_id)
	{
		$('email_notify_product').value = product_id;
		toggleRememberMepopupEmailNotify();
	}
</script>
